/* eslint-disable arrow-body-style */
export default function createMethods(session) {
  return {
    createVisualization: () => session.call('volume.create', ["MPR"]),
    shading: () => session.call('volume.shade', []),
    createNewVisualization: () => session.call('volume.recreate', ["2.25.273770070420816203849299146355226291780", "1.2.840.113619.2.428.3.678656.566.1723853370.188.3"]),
    activeRotate: () => session.call('volume.rotate', []),
    rotateDirection: (direction) => session.call('volume.view.plane', [direction]),
    applyPreset: (name) => session.call('volume.preset', [name]),
    activeLength: () => session.call('volume.length', []),
    activeAngle: () => session.call('volume.angle', []),
    delete: () => session.call('volume.delete', []),
    activeCut: () => session.call('volume.crop', []),
    activeCutFreehand: () => session.call('volume.crop.freehand', ["INSIDE"]),
    removeBed: () => session.call('volume.remove.bed'),
    activePan: () => session.call('volume.pan', []),
    activeZoom: () => session.call('volume.zoom', []),
    resetViewport: () => session.call('volume.reset', []),
    updateResolution: (resolution) => session.call('vtk.cone.resolution.update', [resolution]),
    shift: () => session.call('volume.shift', []),
    dicomDownload: (studyUID, seriesUID) => session.call('volume.recreate', [studyUID, seriesUID]),
    getStatus: () => session.call('dicom.status', []),
    slice3D: (orientation) => session.call('volume.slice', [orientation]),
    flythrough: (operation) => session.call('endo.flythrough', [operation]),
    resetEndo: () => session.call('endo.reset', []),
    spin: (option) => session.call("volume.spin", [option]),
    setCrosslines: () => session.call("mpr.crosslines", []),
    activeWL: () => session.call("mpr.wl", []),
    applyWLPreset: (ww, wl) => session.call("mpr.wl.preset", [ww, wl]),
    test: () => session.call("message", ["Hello"]),
  };
}
